### PR TITLE
initial refactor to follow processing library guidelines

### PR DESCRIPTION
**Pull request by christophertino**
Restructured using the processing library template.  Ant build.xml generates JAR file and javadocs in /distribution folder (ignored).

### CODE REVIEW

**Comment by tildebyte** [comment]
If you don't mind my asking; how did you resolve #75?

**Comment by christophertino** [comment]
@tildebyte I'm brand new to this project so I'm just getting caught up. This commit is mostly scaffolding changes, ant build file, etc. I honestly haven't dug into open issues yet. Our goal is to bring HYPE back into active development and we'd love to get your collaboration as we move forward.

**Comment by tildebyte** [comment]
Cool. The main reason I asked is that this is exactly what I had worked on in the past. The hackarounds I had to do to are in #75 (The worst issue is the `atan2` call on line 100 of *HMagneticField*). The jar I managed to roll up works great, including with Processing's Python mode [[1](https://github.com/tildebyte/processing.py-demos/tree/master/SpinningTop_HYPE)], [[2](https://github.com/tildebyte/processing.py-demos/tree/master/OrbitingSquares_HYPE)]. I think I still have some of the examples which I ported over to Python mode as well.

Let me know how I can help :+1:

**Comment by christophertino** [comment]
That's good to know. We're working now to refactor the main H class into a more traditional constructor pattern. I haven't exactly decided how to approach it yet so if you have any thoughts I'm all ears. After that we'll start on some unit tests and expand the core with some new classes that @hype has built.

**Comment by tildebyte** [comment]
I'm not sure I'm qualified to help at that level, but I am curious as to whether or not you're targeting Processing 3.0+ (which iirc the biggest change in is completely deprecating PApplet).

**Comment by hype** [comment]
Processing 3 + JAVA 8 - that's what we'll be writing against.

**Comment by tildebyte** [comment]
:+1:

**Pull request merged**
